-- Create master_accounts table
CREATE TABLE IF NOT EXISTS public.master_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number TEXT UNIQUE NOT NULL,
    bank TEXT NOT NULL,
    short_code TEXT NOT NULL,
    account_code TEXT NOT NULL,
    description TEXT NOT NULL,
    branch TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create dm_doi_tuong table
CREATE TABLE IF NOT EXISTS public.dm_doi_tuong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT UNIQUE NOT NULL,
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create entities table
CREATE TABLE IF NOT EXISTS public.entities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create accounting_rules table
CREATE TABLE IF NOT EXISTS public.accounting_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT UNIQUE NOT NULL,
    is_thu BOOLEAN DEFAULT FALSE NOT NULL,
    tk_no TEXT,
    tk_co TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create special_rules table
CREATE TABLE IF NOT EXISTS public.special_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition TEXT NOT NULL,
    cut_from TEXT,
    cut_to TEXT,
    format TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS (Row Level Security) on all tables
ALTER TABLE public.master_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dm_doi_tuong ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounting_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.special_rules ENABLE ROW LEVEL SECURITY;
