-- Seed master_accounts
INSERT INTO public.master_accounts (account_number, bank, short_code, account_code, description, branch) VALUES ('8600098886', 'BIDV', 'B8886', '1121B8886', 'TKTG VND BIDV 8600098886', 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN VIỆT NAM - CHI NHÁNH BÌNH CHÁNH') ON CONFLICT (account_number) DO NOTHING;
INSERT INTO public.master_accounts (account_number, bank, short_code, account_code, description, branch) VALUES ('0792901290', 'MB', 'H1290', '1121M1290.LOAN', 'TKTG VND MB BANK 0792901290 (LOAN-NH)', 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN QUÂN ĐỘI') ON CONFLICT (account_number) DO NOTHING;
INSERT INTO public.master_accounts (account_number, bank, short_code, account_code, description, branch) VALUES ('8913152134', 'MB', 'M2134', '1121M2134', 'TKTG VND MB BANK 8913152134', 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN QUÂN ĐỘI') ON CONFLICT (account_number) DO NOTHING;

-- Seed dm_doi_tuong
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('NAM-BV0013', 'BV0013') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('PHI-TX009', 'TX009') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('CAM-TX0011', 'TX0011') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('DAT-TX0012', 'TX0012') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('AN-TX019', 'TX019') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('NAM - BV0013', 'BV0013') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('LOAN-DD002', 'DD002') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('X.ANH-TL0016', 'TL0016') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('Tra tien cho Long', 'BGD002') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('LONG-BGD002', 'BGD002') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('CHAU-BGD001', 'BGD001') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('Tra cho Chau', 'BGD001') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('HIEN-TX020', 'TX020') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('Tra tien cho Chau', 'BGD001') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('FEE-002', '0100150619-189.NHBIDV') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('CE0102650935', '0107500414.VEVETC') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('RENTPARK', 'BAITAN') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('PHI QUAN LY TAI KHOAN 860xxx886', '0100150619-189.NHBIDV') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('PHI BSMS', '0100150619-189.NHBIDV') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('B/O 8600098886', '0100108102-009.DAUPET') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('NAM BV0013', 'BV0013') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('PHI TX009', 'TX009') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('CAM TX0011', 'TX0011') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('DAT TX0012', 'TX0012') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('HIEN TX020', 'TX020') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('REWARD 1ST DAT-TX0012', 'TX0012') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('REWARD 1ST AN-TX019', 'TX019') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('TRUONG THANH PHI', 'TX009') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('TRINH THANH HIEN', 'TX020') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('NGUYEN THI LOAN', 'DD002') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('TON LONG CAM', 'TX0011') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('CONG TY CO PHAN CANG VIET NAM', '0315895749.CAVINA') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('LE VAN DAT', 'TX0012') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('ITC', 'CHECK_AGAIN') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('DEPOT KHO VAN TAN CANG', '0318512521.CAKVTC') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('GREATING FORTUNE LOGISTICS', '0312714296.CAFOTU') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('TRAN DINH PHUC', 'NGOAI 39') ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.dm_doi_tuong (keyword, code) VALUES ('TIEP VAN TAN CANG HMM', 'CHECK_AGAIN') ON CONFLICT (keyword) DO NOTHING;

-- Seed entities
INSERT INTO public.entities (code, name) VALUES ('1100824933', 'CÔNG TY TNHH AN HẠ LONG AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2000483600', 'CÔNG TY CP THƯƠNG MẠI DỊCH VỤ VÀ XUẤT NHẬP KHẨU HUỲNH HƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3501492566', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN THỦY SẢN THÁI BÌNH DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101978213.CPNH', 'CÔNG TY CỔ PHẦN XUẤT NHẬP KHẨU THỦY SẢN TRỌNG NHÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316918893.WWIN', 'CÔNG TY TNHH HỢP TÁC WINWIN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('KHAC.PHHA79', 'PHƯƠNG HÀ 79 ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('AN.VTOUT', 'MAI LOI AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318401941.ANMERA', 'CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ MÊ RAU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3700546488.CABIDU', 'CÔNG TY CỔ PHẦN CẢNG BÌNH DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('NGUYEN.VTOUT', 'TRƯƠNG XUÂN NGUYÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303172752-006.DAUTHI', 'CỬA HÀNG XĂNG DẦU PHÁT THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0308365684.CADTCT', 'CÔNG TY CỔ PHẦN ĐỐI TÁC CHÂN THẬT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317291301.CACTLM', 'CÔNG TY CỔ PHẦN ỨNG DỤNG CÔNG NGHỆ LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('HOAN.VTCPHU', 'TỪ CÔNG HOAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.0314059124.SCNHAN', 'Hộ kinh doanh vá vỏ NHÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3603042580.NDAI', 'CÔNG TY TNHH NGỌC ĐẠI DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0977999789', 'PHỤ TÙNG Ô TÔ ĐỒ CHƠTRANG TRÍ....I') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302571497.DAUKHA', 'DOANH NGHIỆP TƯ NHÂN THƯƠNG MẠI DỊCH VỤ TỔNG AN KHƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101243150.PMMISA', 'CÔNG TY CỔ PHẦN MISA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313025242.MOCWWA', 'CÔNG TY TNHH TIẾP VẬN WINWAY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314715626.ECOT', 'CÔNG TY CỔ PHẦN CÔNG NGHỆ ECOTRUCK') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316669781.CAGNAM', 'CÔNG TY TNHH SITC GIANG NAM LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313551164.GSDP', 'CÔNG TY TNHH GSDP') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312135429.DAPH', 'CÔNG TY TNHH DỊCH VỤ HÀNG HẢI ĐA PHƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315022575.DAUSWP', 'CÔNG TY TNHH XĂNG DẦU TÂY NAM S.W.P') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315426218.MEVI', 'CÔNG TY TNHH MEVIFOOD') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315973122.DAU.AT', 'CÔNG TY TNHH ĐẦU TƯ THƯƠNG MẠI A.T VIỆT NAM GLOBAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4201666044.AUBPHA', 'CÔNG TY TNHH BẾN PHÀ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0108269207.XEBEGR', 'CÔNG TY CỔ PHẦN BE GROUP') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('VECO', 'VÉ CỔNG TẠI DEPOT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301722256.DAUTHI', 'CÔNG TY TNHH THƯƠNG MẠI TÂN HIỆP') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3400393047.TAQY', 'CÔNG TY TNHH THỦY SẢN TÂN QUÝ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0310002046-007.DAUTAN', 'CHI NHÁNH CÔNG TY CỔ PHẦN THƯƠNG MẠI NƯỚC GIẢI KHÁT KHÁNH AN - CỬA HÀNG XĂNG DẦU TÂN AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0309924984.TCHP', 'CÔNG TY CỔ PHẦN CẢNG TÂN CẢNG HIỆP PHƯỚC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313262123.ANHANA', 'CÔNG TY TNHH DỊCH VỤ THẾ GIỚI NƯỚNG (HANA)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312714296.CAFOTU', 'CÔNG TY CỔ PHẦN GREATING FORTUNE LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317400303.CONTHT.RENT', 'CÔNG TY TNHH DỊCH VỤ CƠ KHÍ VÀ LOGISTICS HƯNG THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317363235.HINA', 'CÔNG TY TNHH QUỐC TẾ HIẾU NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTAP6', 'TÂM PHÚC 6') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318503171.VTNGTY', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ THỰC PHẨM NGỌC TỶ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1100108351-105.DAUTNIN', 'CHI NHÁNH PETROLIMEX BẮC TÂY NINH - CÔNG TY TNHH MTV PETROLIMEX TÂY NINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313217924.ANQNEM', 'CÔNG TY TNHH MỘT THÀNH VIÊN NHÀ HÀNG QUÁN NEM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2000527350.TIMA', 'CÔNG TY TNHH MỘT THÀNH VIÊN THỦY SẢN THIÊN MÃ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304998358.TBPHVU', 'CÔNG TY CỔ PHẦN THƯƠNG MẠI - DỊCH VỤ PHONG VŨ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BAITAN', 'LÊ NGỌC TÂN CHO THUÊ MẶT BẰNG ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('6300033769.MPHG', 'CÔNG TY CP THỦY SẢN MINH PHÚ - HẬU GIANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315806442.MIGG', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ MIG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315852382.ANHINO', 'CÔNG TY CỔ PHẦN HINOKO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303172752-008.DAUQE8', 'CHI NHÁNH CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ HIỆP QUẾ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('PMDA', 'LIGHT PARK') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311490822', 'CÔNG TY TNHH ĐẦU TƯ VIETFOODS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('KHAC.RESTSTOP.LASA', 'Trạm dừng chân cao tốc Trung Lương') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('GIANG MISA', 'PHẠM TRƯỜNG GIANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303778092.EMBA', 'CÔNG TY LIÊN DOANH EMBASSY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302712571.CCTMMB', 'CÔNG TY CỔ PHẦN MẮT BÃO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1201622838.TPVI', 'CÔNG TY TNHH XUẤT NHẬP KHẨU THỰC PHẨM VIỆT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316985508.GLAL', 'CÔNG TY TNHH GLORY ALLIANCE') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302608588.CONTQT', 'CÔNG TY CỔ PHẦN THƯƠNG MẠI - DỊCH VỤ - VẬN TẢI QUỐC THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3500354108.ANLOPU', 'DOANH NGHIỆP TƯ NHÂN XĂNG DẦU LONG PHƯỚC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317413863.SCVQUA', 'CÔNG TY TNHH DỊCH VỤ SẢN XUẤT CƠ ĐIỆN VĂN QUANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('PHUC.CAPLON.PLO3', 'LÊ SỸ PHÚC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316799082.CCCMRA', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ ĐIỆN TỬ VIỆT HOÀNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCHTHI', 'Cửa hàng Phụ tùng Ôtô HƯNG THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0309587009.VTHKHA', 'CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ HUYỀN KHẢI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300555450.DAUPSG', 'CÔNG TY TNHH MTV PETROLIMEX SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('082077000265.ANTGIA', 'HỘ KINH DOANH VƯỜN THƯ GIÃN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101879300.MTHI', 'CÔNG TY CỔ PHẦN HẠNH MINH THI - LONG AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300649476-006.DAUCTCP', 'CHI NHÁNH LONG AN- TỔNG CÔNG TY THƯƠNG MẠI KỸ THUẬT VÀ ĐẦU TƯ- CÔNG TY CỔ PHẦN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3703184250.SCTABD', 'CÔNG TY TNHH GARAGE THIÊN ÂN PHÁT BÌNH DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101800371.HNBB', 'CÔNG TY CỔ PHẦN MỸ PHẨM HNB') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314653017', 'DV LỐP TRUNG NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318065707.CCTBLO', 'CÔNG TY TNHH AUTO THÁI BÌNH LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101527385-066.BHBVGD', 'CÔNG TY BẢO VIỆT GIA ĐỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('MINH.CAFOTU', 'TRẦN VĂN MINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('HON.CASINO', 'NGUYỄN THÀNH HƠN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313720408.SELI', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ TIẾP VẬN SEALINK') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0109081952.SNOK', 'CÔNG TY TNHH SNOW KING GLOBAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317960658.POWW', 'CÔNG TY TNHH THƯƠNG MẠI POW') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0106303124.CLBU', 'CÔNG TY TNHH COLOMBUS VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('CONT.DVICDP', 'NGUYỄN MINH KHA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315172595.TQPH', 'CÔNG TY TNHH TM DV SX PHÒNG CHÁY CHỮA CHÁY TÂN QUANG PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318575095', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ NGỌC VY VY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0307209393.PHAT', 'CÔNG TY TNHH ANH PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1402129894.LAVO', 'CÔNG TY TNHH LAVODOTA FOODS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300424088.CABISA', 'CÔNG TY CỔ PHẦN VẬN TẢI BIỂN SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305013204.CATVXA', 'Công ty Cổ phần Tiếp Vận Xanh') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TX009', 'TRƯƠNG THÀNH PHI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317962528.SCAHAO', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VẬN TẢI XÂY DỰNG ANH HÀO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317915197.ANSATI', 'CÔNG TY CỔ PHẦN DỊCH VỤ SATIS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316185734.LEVU', 'CÔNG TY TNHH DỊCH VỤ VẬN TẢI XUẤT NHẬP KHẨU LÊ VƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BOCXEP.KIMSC', 'Bốc xếp kho IMSC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0319118052.SCTQUO', 'CÔNG TY TNHH ĐẦU TƯ THƯƠNG MẠI DỊCH VỤ AUTO THIÊN QUỐC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0108414207.HAPU', 'CÔNG TY TNHH HÀ PHÚ VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314825107.CCVTSG', 'CÔNG TY TNHH VI TÍNH SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316064271.ACES', 'CÔNG TY TNHH GLOBAL ACCESS VIETNAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('.TUNG', 'TÙNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BV0013', 'ĐẶNG VĂN NĂM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0105684477-001.ATAC', 'CHI NHÁNH CÔNG TY TNHH AT Á CHÂU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311609355.TBFPTT', 'Công Ty Cổ Phần Bán Lẻ Kỹ Thuật Số FPT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313908174', 'CÔNG TY TNHH XUẤT NHẬP KHẨU QUỐC TẾ LÊ GIA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4200240380-027.DAUPKH', 'CHI NHÁNH XĂNG DẦU PHÚ YÊN - CÔNG TY XĂNG DẦU PHÚ KHÁNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('62A42242.HGIANG', 'NGÔ HOÀNG GIANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1102050996.SEFO', 'CÔNG TY TNHH JP SEAFOODS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4201565222.VSEA', 'CÔNG TY TNHH VIỆT SEA VN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317307544.CCMIAS', 'CÔNG TY CỔ PHẦN MIOTO ASIA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301471348.COSCOS', 'CÔNG TY TNHH COSCO SHIPPING LINES (VIỆT NAM)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316464216.VTLEVA', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VẬN TẢI LÊ VÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312098128.DAUTAN', 'CÔNG TY TNHH MỘT THÀNH VIÊN KINH DOANH XĂNG DẦU TÂN THỊNH PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315921269.VTKHPH', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ LOGISTIC KHÔI PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303217354-010.TBTGDD', 'CHI NHÁNH CÔNG TY CỔ PHẦN THẾ GIỚI DI ĐỘNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303172752.DAUHQE', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ HIỆP QUẾ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317817753.TCRB', 'CÔNG TY TNHH TIẾP VẬN TOÀN CẦU RUBY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300951119.DIENLU', 'TỔNG CÔNG TY ĐIỆN LỰC THÀNH PHỐ HỒ CHÍ MINH TNHH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314902471.PDAT', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ GIAO NHẬN VẬN TẢI PHÁT ĐẠT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311854540-012.ANCKK1', 'CÔNG TY CỔ PHẦN ĐẦU TƯ VIÊN NGỌC MỚI- CHI NHÁNH NHÀ HÀNG CHANG KANG KUNG 1') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315249470.VTKKAB', 'CÔNG TY TNHH XUẤT NHẬP KHẨU KAB') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('QUE.VTOUT', 'Đỗ văn cao Quế') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311426136.VPGIVR', 'CÔNG TY CỔ PHẦN BÁNH GIVRAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312263124.VPCOOP', 'CÔNG TY TNHH SAIGON CO-OP FAIRPRICE') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BOCXEP.CATCSG.TCHP', 'Bốc xếp ở Tân Cảng Hiệp Phước') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3501371699.DALOSO', 'CÔNG TY TNHH XĂNG DẦU LONG SƠN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0901156725.NHYE', 'CÔNG TY TNHH KHOA NGỌC HƯNG YÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318668649.TANH', 'CÔNG TY TNHH DỊCH VỤ VÀ THƯƠNG MẠI VẬN TẢI TRÚC ANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCPH89', 'Siêu thị Phụ tùng Ô tô PHI 89') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318386852.SCMIKH', 'CÔNG TY TNHH PHỤ TÙNG VÀ SỬA CHỮA MINH KHANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTRA2', 'Vá vỏ TRẠM 2') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318623704.CCMHMK', 'CÔNG TY TNHH THƯƠNG MẠI PHÁT TRIỂN GIA KHANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1801331439.ANTGIA', 'CÔNG TY CỔ PHẦN THƯƠNG MẠI DU LỊCH CẦM THI GIANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('MB.CNPX', 'Ngân hàng TMCP Quân Đội - CN Phú Xuân') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUDO.CATBDU', 'Điều độ cảng Hàng Hải Thái Bình Dương (Pacific Marine)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0102196915-001.TBMETA', 'CHI NHÁNH CÔNG TY CỔ PHẦN MẠNG TRỰC TUYẾN META') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101858332.SCHPPA', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN THƯƠNG MẠI HIỆP PHÚ PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3700347080.SCWSVN', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN WAN SING RADIATOR (VIỆT NAM)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.0314653017.SCTNAM', 'CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ LỐP TRUNG NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('KHAC.3702268638.TIENDAT', 'CÔNG TY TNHH MỘT THÀNH VIÊN THƯƠNG MẠI DỊCH VỤ Ô TÔ VÕ TIẾN ĐẠT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1900643100.THMY', 'CÔNG TY TNHH THỦY SẢN THẢO MY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('086180016457.ANQA64', 'HỘ KINH DOANH QUÁN ĂN 64') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305320484.PMANDU', 'CÔNG TY CỔ PHẦN ĐIỆN TỬ VIỄN THÔNG ÁNH DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('XENANG.CABKHA', 'Xe Nâng Cảng Bảo Khang') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('GRAB.', 'GRAB') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302599608.VTHNGU', 'CÔNG TY TNHH XUẤT NHẬP KHẨU - XÂY DỰNG  & DỊCH VỤ HẢI NGUYÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('6000175829.DALA', 'CÔNG TY CỔ PHẦN CAO SU ĐẮK LẮK') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318969156.VPMPHU', 'CÔNG TY TNHH TM DV TIN HỌC MAI PHƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318266548', 'CÔNG TY TNHH XD TM DV TUẤN PHONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314729876.WRCC', 'CÔNG TY TNHH GIAO NHẬN QUỐC TẾ WRC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314859219.VTOA', 'CÔNG TY CỔ PHẦN VIỆT TOẢN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315534598.FISH', 'CÔNG TY TNHH VIỆT NAM FISHES') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TRUONGDNP', 'TRƯỜNG DNP') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305475230.QUHY', 'CÔNG TY TNHH THƯƠNG MẠI XUẤT NHẬP KHẨU THỦY SẢN QUANG HUY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304853183-001.DAUPTA', 'CHI NHÁNH CÔNG TY CỔ PHẦN ĐẦU TƯ XÂY DỰNG VÀ DỊCH VỤ  KHO BÃI PHÚ TÀI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0106903717.DTHL', 'CÔNG TY CỔ PHẦN ĐẦU TƯ HỢP LỰC 819 VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314690379.DBAO', 'CÔNG TY TNHH LOGISTICS DƯƠNG BẢO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305425568.THIG', 'CÔNG TY TNHH T.H.I GROUP VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303482440.COON', 'CÔNG TY CỔ PHẦN GIAO NHẬN VẬN TẢI CON ONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DUY.CAPLON3', 'PHẠM THẾ DUY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('PHUHIEU', 'NGUYỄN THỊ HOA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316813925.WOWI', 'CÔNG TY TNHH WORLDWIDE LOGISTICS VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('NGA.CAVTQT', 'NGUYỄN THỊ NGA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0308427394.TITY', 'CÔNG TY CỔ PHẦN THỰC PHẨM TINH TÚY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TX019', 'NGUYỄN VĂN AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1702073297.KHTY', 'CÔNG TY TNHH MỘT THÀNH VIÊN KHÁNH HÀ THUẬN YÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('SC.TIRE.KNGU', 'KHÔI NGUYÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCGIAU', 'Vá vỏ HỮU GIÀU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0100283873.NHQDOI', 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN QUÂN ĐỘI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('NUOCBAI', 'Tiền nước tại bãi không có hoá đơn') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTQUA', 'Vá vỏ ô tô THANH QUANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3502208127.GKDK', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN DỊCH VỤ GIẾNG KHOAN DẦU KHÍ TOÀN CẦU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318175770.ANMTOM', 'CÔNG TY TNHH MTV OM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0903233244.PTTHAN', 'PHỤ TÙNG THIÊN ÂN (NGUYỄN VĂN BẢY)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303582935.NHVI', 'CÔNG TY CỔ PHẦN NHẬT VIỆT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316655186.VIRG', 'CÔNG TY CỔ PHẦN VIRGO GLOBAL LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCCUON', 'Cửa hàng CƯỜNG 34') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3401254649.SCBTHU', 'CÔNG TY TNHH MTV XĂNG DẦU BÌNH THUẬN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314194250.AOSH', 'CÔNG TY CỔ PHẦN VẬN TẢI AO SHIPPING') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('CCT.HNB', 'Chi cục thuế Huyện Nhà Bè') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303217354.TBTGDD', 'CÔNG TY CỔ PHẦN THẾ GIỚI DI ĐỘNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315644939.DK5017', 'CÔNG TY CỔ PHẦN ĐĂNG KIỂM 50-17D') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318690570.TSCC', 'CÔNG TY TNHH DỊCH VỤ THỰC PHẨM TSC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCCHUN', 'BẢO CHUNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0109106540.VCDK', 'CÔNG TY TNHH VẬN CHUYỂN DK VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316203655', 'CÔNG TY TNHH T.H.E LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318002753', 'CÔNG TY TNHH GIẢI PHÁP TIẾP VẬN C.H.L') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317343246.ANTHLY', 'CÔNG TY CỔ PHẦN ẨM THỰC THIÊN LÝ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303153414.DAUNCM', 'CÔNG TY TNHH THƯƠNG MẠI NGỌC CHÂU MINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0309528740.BAIVNG', 'CÔNG TY CỔ PHẦN VẠN NIÊN GIA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303168562.VTPTHA', 'CÔNG TY TNHH THƯƠNG MẠI - GIAO NHẬN XUẤT NHẬP KHẨU THÔNG PHƯƠNG THẮNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311936673-003.AND1Q7', 'CHI NHÁNH QUẬN 7 - CÔNG TY CP D1 CONCEPTS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4401029564.MOSC', 'CÔNG TY TNHH MOSC VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313524097.CAICDT', 'CÔNG TY TNHH MỘT THÀNH VIÊN CẢNG ICD TÂY NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305599878.DEQT', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN DEVELING QUỐC TẾ (VIỆT NAM)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317206095.VTHOLO', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VẬN TẢI HOÀN LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0200912772.ATTH', 'CÔNG TY TNHH VẬN TẢI AN TOÀN THẮNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3701939040.SCVDPG', 'CÔNG TY TNHH MỘT THÀNH VIÊN Ô TÔ VIỆT ĐÔNG PHONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101889025-001.DPTA', 'CHI NHÁNH CÔNG TY TNHH THƯƠNG MẠI VÀ DƯỢC PHẨM THÀNH AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4201766761.DAUBNA', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN DỊCH VỤ TUYẾN BẮC NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302047389.HUHA', 'CÔNG TY CỔ PHẦN NÔNG NGHIỆP HÙNG HẬU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301448204-003.VIHU', 'CHI NHÁNH CÔNG TY CỔ PHẦN HƯƠNG LIỆU VIỆT HƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('5800000167-001.VPDLAT', 'CHI NHÁNH CÔNG TY TNHH DALAT HASFARM TẠI THÀNH PHỐ HỒ CHÍ MINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TUYEN.VTOUT', 'LÊ QUỐC NGỌC TUYỀN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3601038204.DAUTIN', 'CÔNG TY CỔ PHẦN XĂNG DẦU TÍN NGHĨA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311041062.TRIV', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ XUẤT NHẬP KHẨU TRÍ VIỆT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301730592-004.ANNGON', 'CHI NHÁNH CÔNG TY TNHH DU HỌC DU LỊCH THƯƠNG MẠI DỊCH VỤ Á ÂU - NHÀ HÀNG QUÁ NGON') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('THANH.CATCSG', 'NGÔ VĂN THANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300954529.CCBCVT', 'CHI NHÁNH TẬP ĐOÀN BƯU CHÍNH VIỄN THÔNG VIỆT NAM (LOẠI HÌNH DOANH NGHIỆP: CÔNG TY TNHH) - VIỄN THÔNG THÀNH PHỐ HỒ CHÍ MINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318159909.PADA', 'CÔNG TY TNHH THƯƠNG MẠI & LOGISTICS PANDA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313862667.CNGU', 'CÔNG TY TNHH PHÁT TRIỂN CAO NGUYÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300447173.CASOMN', 'TỔNG CÔNG TY CỔ PHẦN ĐƯỜNG SÔNG MIỀN NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315895749.CAVINA', 'CÔNG TY CỔ PHẦN CẢNG VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316890870', 'CÔNG TY TNHH THE LOGISTICS GLOBAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101517122.DPVPHC', 'CÔNG TY CỔ PHẦN THANH TOÁN QUỐC GIA VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('HIEU.VTOUT', 'LÊ MINH HIẾU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300514849.CATCSG.TCHP', 'CÔNG TY TNHH MỘT THÀNH VIÊN TỔNG CÔNG TY TÂN CẢNG SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303172752-001.DAUQE1', 'CHI NHÁNH CÔNG TY TNHH  THƯƠNG MẠI DỊCH VỤ HIỆP QUẾ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315050290.SELA', 'CÔNG TY TNHH SEALAND LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCAPHO', 'Vá vỏ ANH PHONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314424031.PLAS', 'CÔNG TY CỔ PHẦN  PLASMA VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1201664884.DAU.TG', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ NGỌC THUẬN TG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101995473.DEHE', 'CÔNG TY TNHH MTV CÔNG NGHIỆP DEHE VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4400361819.BAHA', 'CÔNG TY CỔ PHẦN BÁ HẢI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304791385.CAPLON.PLO3', 'CÔNG TY TNHH CẢNG PHƯỚC LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314050795.ANROYA', 'CÔNG TY TNHH THƯƠNG MẠI QUỐC TẾ HẢI SẢN HOÀNG GIA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('THAN.VTOUT', 'NGUYỄN TRUNG THÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('XENANG.CAXDTC.TCMT', 'Xe Nâng Tân Cảng Mỹ Thuỷ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301746112.HACH', 'CTY TNHH THƯƠNG MẠI HÀ CHÂU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300555450-001.DAUKV2', 'CHI NHÁNH XĂNG DẦU SÀI GÒN - CÔNG TY XĂNG DẦU KHU VỰC II TNHH MỘT THÀNH VIÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311936673-005.AND1BT', 'CHI NHÁNH BÌNH THẠNH - CÔNG TY CỔ PHẦN D1 CONCEPTS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2001363507.HUTH', 'CÔNG TY TNHH THỦY SẢN HUỲNH THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305599879', 'TRANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1601887701.THHA', 'CÔNG TY TNHH XUẤT NHẬP KHẨU THIÊN HẠO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311854540.ANNMOI', 'CÔNG TY CỔ PHẦN ĐẦU TƯ VIÊN NGỌC MỚI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3703233204.SCSLAM', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ LỐP SONG LÂM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3700347081.SCWSVN', 'CÔNG TY TNHH GIAO NHẬN HÀNG HÓA MINH PHƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCHAII', 'Điện - Điện lạnh Ô tô HẢI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.BINH', 'NGUYỄN DUY BÌNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2200159048.KIAN', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN KIM ANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318398262', 'CÔNG TY TNHH KINH DOANH THƯƠNG MẠI PHAN THU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101744864.FIBE', 'CÔNG TY TNHH VIET FIBER') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3702308753.HNGH', 'CÔNG TY TNHH GỖ HẰNG NGHĨA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312563329.NKPU', 'CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI DỊCH VỤ NAM KHẢI PHÚ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101899113.PUHU', 'CÔNG TY TNHH MTV XNK THỦY SẢN PHÚ HƯNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304563533.VPTOVI', 'DOANH NGHIỆP TƯ NHÂN THƯƠNG MẠI DỊCH VỤ MỰC IN TOÀN VĨ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUDO.CAPLON.PLO3', 'Điều độ Cảng Phước Long 3') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUDO.CAXDTC.TCMT', 'Điều độ Tân Cảng Mỹ Thuỷ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCAQUY', 'Đổi ắc quy cũ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('THUY  - SAO TA', 'VÕ HỒNG THỤY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317770505.ANTOCA', 'CÔNG TY CỔ PHẦN TRẢI NGHIỆM TOÀN CẦU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('CAO.VTOUT', 'HOÀNG VĂN CAO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3700333264.HAAN', 'CÔNG TY TNHH HẢI ÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317478571', 'CÔNG TY TNHH MỘT THÀNH VIÊN TÂN THỊNH PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300644051.LOTE', 'CÔNG TY TNHH LOTTERIA VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('QUYET.CAPTV1.VICT', 'LÊ VĂN QUYẾT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312392923.ANSOLL', 'CÔNG TY TNHH S.O.L') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('PHƯƠNG.VTOUT', 'NGUYỄN THỊ THÚY PHƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304277959.LNGU', 'CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ LONG NGUYÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0104093672.BĐVTEL', 'TỔNG CÔNG TY CP BƯU CHÍNH VIETTEL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316893430.ANATQ9', 'CÔNG TY CỔ PHẦN ẨM THỰC Q9') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2001187876.CELI', 'CÔNG TY CP XUẤT NHẬP KHẨU THỦY SẢN CELI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('5800000689-030.DAUPBT', 'CHI NHÁNH PETROLIMEX BÌNH THUẬN - CÔNG TY TNHH MTV PETROLIMEX LÂM ĐỒNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317182542.SCWINI', 'CÔNG TY TNHH WINIFRED VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCQUHO', 'Vá vỏ QUỐC HỘI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0306170873.LASA', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN THỦY SẢN LÂM SANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1900695275.PURE', 'CÔNG TY TNHH XUẤT NHẬP KHẨU AQUAPURE SEAFOOD') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('THUA.CAHTHI', 'TRẦN VĂN THUA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('AOMUA.VPRADO', 'CÔNG TY TNHH SX-TM RẠNG ĐÔNG (RANDO)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302345459.CAVTQT', 'CÔNG TY CỔ PHẦN VẬN TẢI VÀ THƯƠNG MẠI QUỐC TẾ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2001260798.TNHU', 'CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ XUẤT NHẬP KHẨU THẢO NHƯ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318426061.CERA', 'CÔNG TY TNHH SINCERA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUDO.CATCSG', 'Điều độ Tân Cảng Sài Gòn') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0105781350', 'CÔNG TY TNHH THƯƠNG MẠI VÀ XUẤT NHẬP KHẨU AN NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304337291.CAHUDU', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ THIẾT BỊ HƯỚNG DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318398752.LVLO', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ LÊ VƯƠNG LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTRUC', 'Điện Ô tô TRỰC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1301126590.VTBT', 'CÔNG TY TNHH VIỆT TOẢN BẾN TRE') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315744605.VGLO', 'CÔNG TY CP VG LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313770991.SC3QUE', 'CÔNG TY TNHH VẬN TẢI BA QUYỀN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316639882.PNPH', 'CÔNG TY TNHH TIẾP VẬN PHÚC NHUẬN PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('8063002075-001', 'TRƯƠNG BÍCH CHÂU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313103684.PINE', 'CÔNG TY TNHH PINETREE VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUDO.CAHUDU.CLGN', 'Điều độ Cảng Cát Lái Giang Nam') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301117650.QTNG', 'CÔNG TY TNHH QUỐC TẾ NGUYỄN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302596283.DAUCGI', 'CÔNG TY CỔ PHẦN THƯƠNG MẠI VÀ DỊCH VỤ CẦN GIỜ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314963756.TUNO', 'CÔNG TY TNHH XUẤT NHẬP KHẨU TÚ NGỌC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317437776.DAUHTH', 'CÔNG TY TNHH DỊCH VỤ HƯNG THUẬN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BX.DNAI', 'Bãi giữ xe tại Công An Tỉnh Đồng Nai') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2001332851.TOVI', 'CÔNG TY TNHH THƯƠNG MẠI & XUẤT NHẬP KHẨU TÔM VIỆT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BGD001', 'TRƯƠNG BÍCH CHÂU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0108314202', 'CÔNG TY TNHH THƯƠNG MẠI HOA VỸ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2000891864.THTY', 'CÔNG TY TNHH THANH THÚY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0102646635.MTDO', 'CÔNG TY CỔ PHẦN ĐẦU TƯ THƯƠNG MẠI QUỐC TẾ MẶT TRỜI ĐỎ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0310709075.VTTRU', 'CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ VÀ ĐẦU TƯ THÀNH TRUNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314902471', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ GIAO NHẬN VẬN TẢI PHÁT ĐẠT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('PENALTY.LICENSE.RENT.TUAN', 'TRẦN MINH TUẤN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301103908-220.NHSCOM', 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN SÀI GÒN THƯƠNG TÍN - CHI NHÁNH QUẬN 7') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0308884312.TTHI', 'CÔNG TY CỔ PHẦN VẬN TẢI VẠN TRƯỜNG THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315275368.NTLOCH', 'CÔNG TY CỔ PHẦN DƯỢC PHẨM FPT LONG CHÂU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305135227.CCSEAL', 'Công Ty TNHH  Giao Nhận - Vận Tải - Xuất Nhập Khẩu Viễn Đông') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305838163-001.DAUHTA', 'CHI NHÁNH CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ HIỆP TÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301103908-206.NHSABE', 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN SÀI GÒN THƯƠNG TÍN - CHI NHÁNH NHÀ BÈ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0110447520.CHAU', 'CÔNG TY TNHH THƯƠNG MẠI VÀ XUẤT NHẬP KHẨU CHÂU ANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TX0012', 'LÊ VĂN ĐẠT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUCHINH', 'Theo dõi các khoản điều chỉnh (CL giữa chi phí thực và hóa đơn)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315488493.CCESVN', 'CÔNG TY TNHH ESPP VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300604002.VEPPMH', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN PHÁT TRIỂN PHÚ MỸ HƯNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('VIKKI', 'NH TNHH MTV SỐ VIKKI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317419417.THQU', 'CÔNG TY TNHH MTV THUẬN QUYỀN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0319141831.DAUABI', 'CÔNG TY TNHH XĂNG DẦU AN BÌNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('CHINH.VTOUT', 'NGUYỄN VĂN CHÍNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.0312726372.SCQCTP', 'Trần Dũng Sĩ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('92002345678..CCSEAL', '92002345678..CCSEAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1101901122.KAJTT', 'CÔNG TY TNHH MTV AJ TOTAL VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316675834.VTSANH', 'CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ VẬN TẢI HOÀNG SONG ANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4500628551.DAU.18', 'CÔNG TY TNHH XĂNG DẦU SỐ 18 NINH THUẬN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4200733964.AUNTRA', 'CÔNG TY CỔ PHẦN ĐẦU TƯ DU LỊCH EUROWINDOW NHA TRANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0319141830.SCHAVU', 'CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI DỊCH VỤ HÀO VƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318512521.CAKVTC', 'CÔNG TY CỔ PHẦN DEPOT KHO VẬN TÂN CẢNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0306943481.NCHI', 'CÔNG TY TNHH THƯƠNG MẠI THỦY SẢN NGUYỄN CHI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCVV24', 'Cơ sở vá xe LƯU ĐỘNG 24/24') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311423350.VTCPHU', 'CÔNG TY TNHH MỘT THÀNH VIÊN DỊCH VỤ VẬN TẢI CHUNG PHƯỚC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0310793207.AELL', 'CÔNG TY TNHH THƯƠNG MẠI & DỊCH VỤ AEL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCNGHO', 'Điện - Máy lạnh Ô tô NGUYỄN HOÀNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311854540-006.ANCKKE', 'CÔNG TY CỔ PHẦN  ĐẦU TƯ VIÊN NGỌC MỚI – CHI NHÁNH NHÀ HÀNG CHANG KANG KUNG EMART') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCKTHI', 'KHANG THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2000574632.TNNH', 'CÔNG TY TNHH THỦY SẢN TRỌNG NHÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0977999785.PHICS2', 'PHI89 CS2 LÊ PHỤNG HIỂU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCONAM', 'Điện Ô tô NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCNGHI', 'Vá vỏ HOÀNG NGHIỆP') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318251887.VTLTPA', 'CÔNG TY TNHH THƯƠNG MẠI VÀ VẬN TẢI LỘC TIẾN PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('VUONG.CAFOTU', 'NGUYỄN THANH VƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCQDIC', 'Tiệm Điện QUỐC ĐÍCH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313505746-006.AUNISO', 'CHI NHÁNH 7 CÔNG TY CỔ PHẦN NISO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315870991.ANMALA', 'CÔNG TY TNHH MTV BÒ MÁI LÁ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300514849.CATCSG', 'CÔNG TY TNHH MỘT THÀNH VIÊN TỔNG CÔNG TY TÂN CẢNG SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314159369.INDO', 'CÔNG TY TNHH RIGEL TECHNOLOGY (INDOCHINA)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0306370738-001.DK5008', 'TRUNG TÂM ĐĂNG KIỂM XE CƠ GIỚI 50-08D') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4401005193.TOVA', 'CÔNG TY CỔ PHẦN THỦY SẢN TÔM VÀNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0306722034.VTVAAN', 'CÔNG TY CỔ PHẦN VẬN TẢI XẾP DỠ THƯƠNG MẠI VẠN AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTOLO', 'TÔ LỐP') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3603899914.ASIA', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN ASIAN BLENDING') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0109746597.ORIF', 'CÔNG TY TNHH THƯƠNG MẠI & XUẤT NHẬP KHẨU ORIFOOD VN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2100311235.LOTO', 'CÔNG TY CỔ PHẦN  ĐÔNG LẠNH THỦY SẢN LONG TOÀN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317627777.VPTOVI', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ THIẾT BỊ VĂN PHÒNG TOÀN VĨ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301776205.VINA', 'CÔNG TY CỔ PHẦN LOGISTICS VINALINK') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316202595', 'CÔNG TY TNHH XUẤT NHẬP KHẨU THỦY SẢN TRỌNG TÍN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BHXH.NB', 'Bảo hiểm xã hội Huyện Nhà Bè') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0309103635.NHSHAN', 'NGÂN HÀNG TNHH MỘT THÀNH VIÊN SHINHAN VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303366525.TRAN', 'CÔNG TY CỔ PHẦN TRANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312788481.CCICOM', 'CÔNG TY CỔ PHẦN IVIVU.COM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4200445412.DAUVQU', 'CÔNG TY TNHH MTV THƯƠNG MẠI VƯƠNG QUYỀN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311089603.TELO', 'CÔNG TY TNHH QUANTERM LOGISTICS VIETNAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BGD002', 'NGUYỄN BÌNH LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4200240380.DAUPKH', 'CÔNG TY XĂNG DẦU PHÚ KHÁNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUDO.CAVTQT', 'Điều độ cảng Vận tải và Thương mại Quốc tế') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BD.DIDO', 'ĐIỀU ĐỘ ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315087540.CCAQNA', 'CÔNG TY TNHH ẮC QUY NGUYÊN ANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302538718.MCTR', 'CÔNG TY TNHH GIAO NHẬN VẬN TẢI QUỐC TẾ MC TRANS (VIỆT NAM)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304563607.DAUTAM', 'CÔNG TY CỔ PHẦN SẢN XUẤT - DỊCH VỤ TÂN BÌNH TANIMEX') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BOCXEP.KTTAO', 'Bốc xếp kho Tân Tạo') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301340497-035.DGBITS', 'CÔNG TY TNHH SẢN XUẤT HÀNG TIÊU DÙNG BÌNH TIÊN - CHI NHÁNH BITI''S TẠI MIỀN NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCMNGO', 'Vá vỏ xe hơi MINH NGỌC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301624033-001.DAULAN', 'CHI NHÁNH CÔNG TY TNHH VẬN TẢI XĂNG DẦU VĨ PHONG TẠI TỈNH LONG AN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312880039.CONTHT', 'CÔNG TY TNHH VẬN TẢI VÀ LOGISTICS HƯNG THỊNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2001342602.DONA', 'CÔNG TY TNHH XUẤT NHẬP KHẨU THỦY SẢN ĐÔNG NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312696223.SCSS', 'CÔNG TY TNHH VẬN TẢI SCS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTHIA', 'Phụ tùng ô tô THIÊN ÂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0106869738-005.ĐTVNPT', 'Trung tâm Kinh doanh VNPT thành phố Hồ Chí Minh - Chi nhánh Tổng công ty Dịch vụ Viễn thông') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301429314.DAUHHI', 'DOANH NGHIỆP TƯ NHÂN THƯƠNG MẠI HÒA HIỆP') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3801063543.DAUVHU', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ SẢN XUẤT VIỆT HÙNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0308365684.CACTLM', 'CÔNG TY CỔ PHẦN ĐỐI TÁC CHÂN THẬT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313046468.DARY', 'CÔNG TY TNHH THỰC PHẨM DARY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0307412162.VTDOTU', 'CÔNG TY TNHH VẬN TẢI ĐÔNG TÚ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0100150619-189.NHBIDV', 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN VIỆT NAM - CHI NHÁNH BÌNH CHÁNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314975293', 'CÔNG TY TNHH  JANG GOON') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DIEUDO.CATCIT', 'Điều độ Cảng Cái Mép') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('XENANG.CATBDU', 'Xe Nâng Cảng Thái Bình Dương') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('CATDAU', 'PHÍ CẮT ĐẦU TÀI XẾ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4200240380-011.DAUNIT', 'CHI NHÁNH XĂNG DẦU NINH THUẬN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304875444.CAXDTC', 'CÔNG TY CỔ PHẦN ĐẠI LÝ GIAO NHẬN VẬN TẢI XẾP DỠ TÂN CẢNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305924567.FILM', 'CÔNG TY TNHH DỊCH VỤ HÀNG HÓA PHIM CHÍNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0100108102-009.DAUPET', 'CHI NHÁNH THÀNH PHỐ HỒ CHÍ MINH CÔNG TY CỔ PHẦN THIẾT BỊ XĂNG DẦU PETROLIMEX') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101360697.PMBKAV', 'CÔNG TY CỔ PHẦN BKAV') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315663480.TUHO', 'CÔNG TY CỔ PHẦN XUẤT NHẬP KHẨU TƯỜNG HOA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('GIANG.VTOUT', 'HỒ THỊ GIANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES (' 0313896754.VTDKLO', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ DUNG KIM LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TOAN.TALOAN', 'Tòa án nhân dân thành phố Tân An tỉnh Long An') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0104076740.NLAM', 'CÔNG TY TNHH THƯƠNG MẠI & XUẤT NHẬP KHẨU NHẤT LÂM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316675802.SINE', 'CÔNG TY TNHH SINEL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('THANG.CATCMT', 'LÊ ĐẠI THẮNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300450673.DAUXDAU', 'CÔNG TY CỔ PHẦN VẬT TƯ - XĂNG DẦU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4401067104.DDVA', 'CÔNG TY TNHH THỦY HẢI SẢN ĐẠI DƯƠNG VÀNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCPVAN', 'PHÁP VĂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCKETH', 'Cơ sở vỏ xe Kế Thịnh') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTLPA', 'Vỏ lốp ô tô TÀI LỘC PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('NEOXE', 'PHÍ NEO TÀI XẾ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0100686210-002.DTMOBI', 'CÔNG TY DỊCH VỤ MOBIFONE KHU VỰC 2 - CHI NHÁNH TỔNG CÔNG TY VIỄN THÔNG MOBIFONE') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313748932.ANTOFO', 'CÔNG TY TNHH TOP FOOD VIET NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317125897.ANGODO', 'CÔNG TY TNHH GOBCHANGE DODOOG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCKHVY', 'KHÁNH VY') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('RACBAI', 'HTX NN DV MÔI TRƯỜNG NHÀ BÈ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305563335.VTTANU', 'CÔNG TY TNHH TÂM NHƯ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300602277.CAPTV1', 'Công ty Liên Doanh Phát Triển Tiếp Vận Số 1') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0202211758.FAST', 'CÔNG TY CỔ PHẦN ĐẦU TƯ THƯƠNG MẠI VÀ GIAO NHẬN F.A.S.T') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2200208753.SATA', 'CÔNG TY CỔ PHẦN THỰC PHẨM SAO TA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303490096.ZALOVN', 'CÔNG TY CỔ PHẦN VNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312365239.PANA', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN LOGISTICS PANAKOR VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1801772507.MEKO', 'CÔNG TY TNHH THỰC PHẨM MEKONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TX0011', 'TÔN LONG CẢM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1702039715.VLKG', 'CÔNG TY TNHH VIỆT LONG KIÊN GIANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0309722120.HOMA', 'CÔNG TY TNHH TIẾP VẬN HOA MAI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318254937.VCTT', 'CÔNG TY TNHH THƯƠNG MẠI VÀ VẬN CHUYỂN THANH THẢO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304741634.VPLOTE', 'CÔNG TY CỔ PHẦN TRUNG TÂM THƯƠNG MẠI LOTTE VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4201613155.UYTI', 'CÔNG TY TNHH THỦY SẢN UY TIẾN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0108392659-001.ANDILA', 'CÔNG TY TNHH HAI DI LAO VIET NAM HOLDINGS - CHI NHÁNH THÀNH PHỐ HỒ CHÍ MINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315762121.TTTT', 'CÔNG TY TNHH GIẢI PHÁP KỸ THUẬT TRANG TRẠI THÀNH TIẾN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3702289349.VTPHUN', 'CÔNG TY TNHH MỘT THÀNH VIÊN TIẾP VẬN VẬN TẢI PHÚ HƯNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1200253539.DAUCTH', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN TMDV XĂNG DẦU CHÂU THÀNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2100307704.CULO', 'CÔNG TY CỔ PHẦN THỦY SẢN CỬU LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2800123406.THOA', 'CÔNG TY CỔ PHẦN XUẤT NHẬP KHẨU THỦY SẢN THANH HÓA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BOCXEP.KLOTE', 'Bốc xếp kho Lotte') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313717155.ADVL', 'CÔNG TY TNHH ADVANTAGE LOGISTICS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCNSIN', 'CÔNG TY TNHH ĐẦU TƯ THƯƠNG MẠI DỊCH VỤ AUTO NHẤT SINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101527385-047.BHBVSG', 'CÔNG TY BẢO VIỆT SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316431115.VTPPPP', 'CÔNG TY TNHH GIAO NHẬN VÀ VẬN TẢI THUẬN THÀNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317711179.ABKK', 'CÔNG TY TNHH XUẤT NHẬP KHẨU ABK') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305938425.TOPP', 'CÔNG TY CỔ PHẦN TOPPS HOANCHAU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313801632.VTPDAT', 'CÔNG TY TNHH TIẾP VẬN PHÁT ĐẠT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312239040.VAMI', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN PHÁT TRIỂN VÂN MINH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.HAI', 'VÕ PHƯỚC HẢI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('KHAC.PENALTY.POLICE.NVL', 'CSGT đường Nguyễn Văn Linh (Tân Tạo-Bình Chánh)') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300555450.DAUKV2', 'CÔNG TY XĂNG DẦU KHU VỰC II TNHH MỘT THÀNH VIÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('NAM.CATCSG', 'TRẦN QUANG TRUNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316780596', 'CÔNG TY TNHH HẢI SẢN TÂM LÊ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318561906', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ MAI VĂN CHÍNH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4201197346.VTHGIA', 'CÔNG TY TNHH DỊCH VỤ VẬN TẢI HOÀNG GIA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('PENALTY.CAMERA', 'KHÔNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.NHAN', 'ĐỖ VĂN NHÀN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3700146497.DAUHPU', 'CÔNG TY TNHH MỘT THÀNH VIÊN THƯƠNG MẠI HIỆP PHÚ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DD002', 'NGUYỄN THỊ LOAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316991861.CAICDP', 'CÔNG TY TNHH ICD PHÚC LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0311854540-009.ANCKKV', 'CÔNG TY CỔ PHẦN ĐẦU TƯ VIÊN NGỌC MỚI- CHI NHÁNH NHÀ HÀNG CHANG KANG KUNG VẠN HẠNH MALL') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('GIANG.CAFOTU', 'HỒ THỊ GIANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305349388-023.ANLEKI', 'CHI NHÁNH CÔNG TY TNHH QUỐC TẾ LÊ KIÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317164092.TCGS', 'CÔNG TY TNHH GIAO NHẬN TOÀN CẦU GS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313444148.CONTBK', 'CÔNG TY TNHH VẬN TẢI BẢO KHANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE', 'KHÔNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304791385.CAPLON', 'CÔNG TY TNHH CẢNG PHƯỚC LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCHLON', 'Vá vỏ lưu động HUỲNH LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3703214240.VPVSIN', 'CÔNG TY TNHH NH FOOD&BEER GARDEN THẮNG VIỆT SING') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('ANH.VTOUT', 'PHẠM THỊ KIM ANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0300555450-009.DAUPVT', 'CHI NHÁNH PETROLIMEX VŨNG TÀU - CÔNG TY TNHH MTV PETROLIMEX SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305736891.CAKTTC', 'CÔNG TY CỔ PHẦN DỊCH VỤ KỸ THUẬT TÂN CẢNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101597777.TBDU', 'CÔNG TY CỔ PHẦN VẬN TẢI QUỐC TẾ THÁI BÌNH DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3502208128.HINO', 'CÔNG TY CỔ PHẦN HINOKO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316966953.BANA', 'CÔNG TY TNHH GROWIN BANA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1400460395.DOME', 'CÔNG TY CP XUẤT NHẬP KHẨU Y TẾ DOMESCO') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('SC.BALE', 'HOÁ ĐƠN BÁN LẺ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2001376143.TOME', 'CÔNG TY TNHH XUẤT NHẬP KHẨU TÔM MEKONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315769624.TTFO', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ T&T FOODS') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0102721191-001.ANGDEN', 'CÔNG TY CỔ PHẦN TẬP ĐOÀN GOLDEN GATE - CHI NHÁNH MIỀN NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317018133.VTPPPP', 'CÔNG TY TNHH TM DV VẬN TẢI P & P') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4201798065.HLNT', 'CÔNG TY TNHH HOÀNG LAI NHA TRANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313444469.SC1001', 'CÔNG TY TRÁCH NHIỆM HỮU HẠN ẮC QUY NGÀN LẺ MỘT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('LATVAT', 'ăn uống chi tiêu cá nhân') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCVVLD', 'VÁ VỎ LƯU ĐỘNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318262670.AQUA', 'CÔNG TY TNHH THƯƠNG MẠI SẢN XUẤT & XUẤT NHẬP KHẨU MINH PHÁT AQUA') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318485853', 'CÔNG TY TNHH PHÁT TRIỂN THƯƠNG MẠI VÀ DỊCH VỤ KIM SANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318369568.MIPH', 'CÔNG TY TNHH GIAO NHẬN HÀNG HÓA MINH PHƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TX020', 'TRỊNH THANH HIỂN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0107500414.VEVETC', 'CÔNG TY TNHH THU PHÍ TỰ ĐỘNG VETC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303533783.VTAPHO', 'CÔNG TY TNHH DỊCH VỤ VẬN TẢI ANH PHONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.SCTHQU', 'Gara THIÊN QUỐC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3700714012-006.DAUVTR', 'CHI NHÁNH 6 CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ VÂN TRÚC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318484715.KBHUTH', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VẬN TẢI VÀ KHO BÃI CÁT LÁI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318441486-002.AUGPFC', 'CHI NHÁNH THÀNH PHỐ HỒ CHÍ MINH - CÔNG TY TNHH GPFC.VN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.DK5017', 'TRẦN MINH TÂM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318302228.VTYKHA', 'CÔNG TY TNHH TM DV - VT YẾN KHANG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3603654777.VTTCON', 'CÔNG TY TNHH LOGISTICS THUẬN THÀNH CÔNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('2300778517.LIMO', 'CÔNG TY CỔ PHẦN SẢN XUẤT VÀ THƯƠNG MẠI LIMO VIỆT NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0314902472.CONTHH.BUY', 'CÔNG TY TNHH TM & DV HOA HÙNG PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304791385.CAPLON.PLO1', 'CÔNG TY TNHH CẢNG PHƯỚC LONG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('BANLE.TRIEU', 'HOÀNG HẢI TRIỀU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('6400350560.DAU.48', 'CÔNG TY TNHH  IQ 48') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0312571129.MEGA', 'CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI XUẤT NHẬP KHẨU QUỐC TẾ MEGARISE') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0202156955.VTTPHA', 'CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ VẬN TẢI NGỌC TOÀN PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('TL0016', 'NGUYỄN BÁ XUÂN ANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0305673056.CATBDU', 'CÔNG TY TNHH THIẾT BỊ VÀ DỊCH VỤ HÀNG HẢI THÁI BÌNH DƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('KHAC.PENALTY.POLICE.CAUPHUXUAN', 'Quá tải khi qua cầu Phú Xuân') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0309788756.CASOTH', 'CÔNG TY CỔ PHẦN TIẾP VẬN MIỀN NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0318928086.VTKTPH', 'CÔNG TY TNHH GIAO NHẬN VẬN TẢI KIÊN TRỰC PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4200943464.CATI', 'CÔNG TY TNHH CÁT TIÊN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('CONT.DOI', 'NGUYÊN VĂN DŨNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0310977525.CUQO', 'CÔNG TY TNHH GIAO NHẬN VẬN TẢI CƯỜNG QUỐC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0302758826.HALO', 'CÔNG TY TNHH THƯƠNG MẠI HẢI LỘC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('4401068771.THDU', 'CÔNG TY TNHH ĐỒ HỘP THANH DUNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('1602148407.DDXA', 'CÔNG TY TNHH MỘT THÀNH VIÊN XUẤT NHẬP KHẨU ĐẠI DƯƠNG XANH') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0303281455.FAGI', 'CÔNG TY CỔ PHẦN FAGI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301455353.DAUQU7', 'CÔNG TY TNHH MỘT THÀNH VIÊN DỊCH VỤ CÔNG ÍCH QUẬN 7') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313932843.DAUAHA', 'CÔNG TY TNHH MTV XĂNG DẦU AN HẠ') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0313224939.DAULHO', 'CÔNG TY TNHH VẬN TẢI DẦU KHÍ LÊ HOÀNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0315707427.VTSTHU', 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VẬN TẢI SONG THƯƠNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0101243150-221.XUAANH', 'CÔNG TY CỔ PHẦN ABC') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0304132047.VPFAHA', 'Công ty cổ phần phát hành sách TPHCM - Fahasa') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('DUNG.VTOUT', 'HOÀNG TRUNG DŨNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3702931090.GPHOPA', 'HỢP TÁC XÃ THƯƠNG MẠI DỊCH VỤ DU LỊCH VŨ HỒNG PHÁT') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0316625907.ROAC', 'CÔNG TY TNHH TIẾP VẬN RỒNG Á CHÂU') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0301447874.DASGON', 'CÔNG TY CỔ PHẦN THƯƠNG MẠI NAM SÀI GÒN') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('3600247325.DAUDNA', 'CÔNG TY XĂNG DẦU ĐỒNG NAI') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.entities (code, name) VALUES ('0317165184.CAHHPH', 'CÔNG TY TNHH DỊCH VỤ HÀNG HẢI PHÚ HƯNG') ON CONFLICT (code) DO NOTHING;

-- Seed accounting_rules
INSERT INTO public.accounting_rules (keyword, is_thu, tk_no, tk_co) VALUES ('PHI CHUYEN TIEN', false, '642', NULL) ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.accounting_rules (keyword, is_thu, tk_no, tk_co) VALUES ('BANK FEE', false, '642', NULL) ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.accounting_rules (keyword, is_thu, tk_no, tk_co) VALUES ('TAM UNG', false, '141', NULL) ON CONFLICT (keyword) DO NOTHING;

-- Seed special_rules
INSERT INTO public.special_rules (condition, cut_from, cut_to, format) VALUES ('CUSTOMER MBCT', 'MBCT', 'D2', '{KEYWORD} - {MATCH}');
INSERT INTO public.special_rules (condition, cut_from, cut_to, format) VALUES ('CUSTOMER POSRETAIL', '', '', '{KEYWORD} thanh toán cho {NAME}');
INSERT INTO public.special_rules (condition, cut_from, cut_to, format) VALUES ('CUSTOMER&&DEN:', 'CUSTOMER', 'DEN:', '{KEYWORD} - {MATCH}');
